@isTest
private class TestRestrictContactByName {
    @isTest static void createcontact(){
    // Test data setup contact with last name is invalid name
    Test.startTest();
    Contact con = new Contact(LastName ='INVALIDNAME');
    Database.UpsertResult result = Database.upsert(con,false);
        Test.stopTest();
        // Verify 
        // In this case the contact creation should have been stopped by the trigger,
        // so verify that we got back an error.
        System.assert(!result.isSuccess());
        System.assert(result.getErrors().size() > 0);
        System.assertEquals('The Last Name "INVALIDNAME" is not allowed for DML.' ,result.getErrors()[0].getMessage());
      }
}